GET http://localhost:8080

###

GET http://localhost:8080/boys

###

GET http://localhost:8080/girls

###

GET http://localhost:8080/persons/search

###

GET http://localhost:8080/persons/search/findDistinctValues

###